server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-chain: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: movie-service-route
          uri: http://movie-api:8081
          predicates:
            - Path=/movies/**, /posters/**, /auth/**, /payments/**