spring:
  cloud:
    gateway:
      default-filters:
        - name: DedupeResponseHeader
          args:
            strategy: RETAIN_FIRST
            name: Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-chain: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: movie-service-route
          uri: http://movie-api:8081
          predicates:
            - Path=/movies/**, /posters/**, /auth/**